export const ADD_PROGRAMARE = "ADD_PROGRAMARE";
export const SELECT_PROGRAMARE = "SELECT_PROGRAMARE";
export const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE";
export const SELECT_DATE = "SELECT_DATE";
export const FETCH_PROGRAMARI_SUCCESS = "FETCH_PROGRAMARI_SUCCESS";
export const FETCH_PROGRAMARI_STARTED = "FETCH_PROGRAMARI_STARTED";
